### ISSUE TITLE
TMDb's server Vidsrc.to not working

### ISSUE THREAD

**Issue by intellimediatv** [stantanasi/streamflix#140]
### Description

No sources found for tv series and movies again on TMDB provider

### Provider

TMDB

### Reproduction steps

click on provider then selecr movie or tv show 
error "no extractors found"

### Operating system

Nvidia Shield Android TV OS version 11.0

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by rickhomes** [comment]
the issue is caused by vidplay keys [endpoint](https://raw.githubusercontent.com/KillerDogeEmpire/vidplay-keys/keys/keys.json) which returns 404

```kotlin
val encodeId = encodeId(id, service.getKeys(key))
```

**Comment by Gabiru34** [comment]
Yeah it's down

**Comment by Gabiru34** [comment]
> the issue is caused by vidplay keys [endpoint](https://raw.githubusercontent.com/KillerDogeEmpire/vidplay-keys/keys/keys.json) which returns 404
> 
> ```kotlin
> val encodeId = encodeId(id, service.getKeys(key))
> ```

Is there a way to fix it?

**Comment by jmaxph** [comment]
How to fix?

**Comment by stantanasi** [comment]
For now, I recommend using the SFlix provider, instead of the TMDb provider.

**Comment by stantanasi** [comment]
**Fixed for now on Release 1.6.7**
Thanks to @rickhomes ❤️ !

**Comment by oathzed** [comment]
> **Fixed for now on Release 1.6.7** Thanks to @rickhomes ❤️ !

This is great you got it working again. But this shows the importance of having multiple providers added to the TMDb provider, lemme know if you need any help finding more. Something that you can look into is sudoflix, it's open source and has actively maintained providers

**Comment by AkashKrx** [comment]
It's down again. Getting http 403 error.

**Comment by oathzed** [comment]
Might be the keys constantly changing. Maybe this is useful? https://github.com/Ciarands/vidsrc-keys

**Comment by stantanasi** [comment]
> Might be the keys constantly changing. Maybe this is useful? https://github.com/Ciarands/vidsrc-keys

Thanks a lot, I couldn't fix it  before because of the keys so I'll see.

Right now it's because the website ask for a token, but I don't know yet how to find it.
Example: https://vidsrc.to/ajax/embed/episode/LoVcnrGv/sources?token=OTo39fhitRA%3D

**Comment by oathzed** [comment]
> > Might be the keys constantly changing. Maybe this is useful? https://github.com/Ciarands/vidsrc-keys
> 
> Thanks a lot, I couldn't fix it before because of the keys so I'll see.
> 
> Right now it's because the website ask for a token, but I don't know yet how to find it. Example: https://vidsrc.to/ajax/embed/episode/LoVcnrGv/sources?token=OTo39fhitRA%3D

No problem.

Hmm yeh I'm not too sure about that, the link I shared they have a discord with devs in it, maybe they'd have an idea?

**Comment by stantanasi** [comment]
Will look into it

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.9**

Thanks @oathzed for the link, it helped me A LOT

**Comment by fikrydev** [comment]
I just updated to 1.6.9 and still having the same issue, SFlix provider is returning error too

**Comment by stantanasi** [comment]
> I just updated to 1.6.9 and still having the same issue, SFlix provider is returning error too

Fixed on TMDb provider as writed on the issue title

SFlix provider is this issue #148 not fixed yet!!!!

**Comment by AkashKrx** [comment]
Still not working to the point its not usable. Very few movies/tvshows are working and not all episodes. One day they are playable another day they stop working

**Comment by stantanasi** [comment]
> Still not working to the point its not usable. Very few movies/tvshows are working and not all episodes. One day they are playable another day they stop working

Works fine for me!! What movies not working and what is your error message

**Comment by AkashKrx** [comment]
@stantanasi  Deadpool & Warefolf

Jessica johones season 2 episode 1 was not working and then next day it worked and then episode 2 is not working.
