### ISSUE TITLE
Featured items time on screen

### ISSUE THREAD

**Issue by oathzed** [stantanasi/streamflix#170]
### Description

Currently the featured items are on screen for 5 seconds, I've noticed that it's on the screen for 5 seconds, it'll go to the next item for 1 second then go to the next item for 5 seconds again and repeat like that.

Currently that's not even enough time to read the synopsis, I'd say it should be changed to like 20 seconds atleast  would be nice if there's user interaction on the screen, then that time gets reset or something, so don't have to keep toggling through them to read that item again.

### Provider

tmdb

### Reproduction steps

1. Be in home screen
2. Watch how fast the featured list goes through itself, without touching anything.

### Operating system

Shield android tv

### Please confirm the following

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] If related to a provider, I have checked the site and it works, but not the app.

**Comment by champvikash** [comment]
20 seconds isn't to much ? @stantanasi @oathzed

**Comment by stantanasi** [comment]
I was thinking more 10 seconds, I too believe that 20 seconds could be a lot
But I will have to see what is the best when I will test it

**Comment by champvikash** [comment]
ok

**Comment by stantanasi** [comment]
@oathzed Just checked my code, it seems that I put 8 seconds to change featured items. I think there is a problem with the timer, same as #171

**Comment by stantanasi** [comment]
**Fixed on Release 1.6.12**

**Comment by oathzed** [comment]
> > I've noticed that it's on the screen for 5 seconds, it'll go to the next item for 1 second then go to the next item for 5 seconds again and repeat like that.
> 
> Should be fixed
> 
> > I'd say it should be changed to like 20 seconds atleast
> 
> I changed it to 12 seconds, you tell me if you prefer more

Nice one man. Its definitely better. Im a pretty average reader and I still can't fully read some of the synopsis and I think having it at 15 seconds would make it so I could, but on the other end, maybe 12 seconds is a good middle ground Incase people would prefer to just glance at titles as they change somewhat quickly now.
