### ISSUE TITLE
Rido movies stoped working

### ISSUE THREAD

**Issue by mubashir86** [stantanasi/streamflix#402]
### Description

"Can't retrieves source" toast is showing when trying to play from Rido Tv. 

### Provider

RidoTV

### Reproduction steps

Open App.
Select Rido Movie
Click on and Movie 
In deatils screen click on Watch now
Video Player appears and show error toast.

### Operating system

Chrome Cast Tv, Pixel 5

### Logs

```bash

```

### Please confirm the following

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] If related to a provider, I have checked the site and it works, but not the app.

**Comment by intellimediatv** [comment]
Rido movies stopped working again no movies are playing one particular error hd_dc_hello_string

**Comment by Paduu29** [comment]
It's like a cat and mouse game.
fixed again in #418

**Comment by intellimediatv** [comment]
Unfortunately even with the new 1.733 release today Rido still not working for movies...is it possible to focus on the other English Providers StreamFlix and TMDB as well when the app got created these other 2 worked well but has been months of playback issues with those also

**Comment by Paduu29** [comment]
I sadly can't do anything for Sflix since I have no API keys for it, that is something that the creator should be able to do. I haven't used TMDB yet, might look into it when I have some time 
As for rido, they change it faster than the fixes, someday we might not longer have that problem but who knows
